# Generated by Django 5.2.7 on 2026-01-02 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('brand', 'brand'), ('blogger', 'blogger')], default='brand', max_length=20),
        ),
        migrations.CreateModel(
            name='BloggerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('platforms', models.CharField(blank=True, default='', max_length=200)),
                ('niche', models.CharField(blank=True, default='', max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('sphere', models.CharField(blank=True, default='', max_length=120)),
                ('budget', models.CharField(blank=True, default='', max_length=120)),
                ('inn', models.CharField(blank=True, default='', max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='accounts.profile')),
            ],
        ),
    ]
