# Generated by Django 5.2.7 on 2026-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_about_profile_avatar_profile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloggerprofile',
            old_name='niche',
            new_name='formats',
        ),
        migrations.RenameField(
            model_name='bloggerprofile',
            old_name='platforms',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='platform_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
