# Generated by Django 5.2.7 on 2026-01-12 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_conversation_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read_by_blogger',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='blogger',
            field=models.ForeignKey(limit_choices_to={'role': 'blogger'}, on_delete=django.db.models.deletion.CASCADE, related_name='blogger_conversations', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'role': 'brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='brand_conversations', to='accounts.profile'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('brand', 'blogger'), name='uniq_brand_blogger_conversation'),
        ),
    ]
