# Generated by Django 5.2.7 on 2026-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_read_message_read_by_blogger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
