# Generated by Django 5.2.7 on 2026-01-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar_bytes_profile_avatar_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
