# Generated by Django 5.2.7 on 2026-01-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bloggerprofile_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
