# Generated by Django 5.2.7 on 2026-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_brandprofile_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '—'), ('female', 'female'), ('male', 'male')], default='', max_length=10),
        ),
    ]
