# Generated by Django 5.2.7 on 2026-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Не проверен'), ('approved', 'Проверен'), ('rejected', 'Не одобрен')], default='pending', max_length=10),
        ),
    ]
