# Generated by Django 5.2.7 on 2026-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_bytes',
            new_name='avatar_blob',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
