# Generated by Django 5.2.7 on 2026-05-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_avatar_bytes_profile_avatar_blob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принята'), ('declined', 'Отклонена')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(limit_choices_to={'role': 'blogger'}, on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_blogger', to='accounts.profile')),
                ('brand', models.ForeignKey(limit_choices_to={'role': 'brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_brand', to='accounts.profile')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='accounts.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'blogger', 'status'], name='accounts_de_brand_i_23e089_idx')],
            },
        ),
    ]
