# Generated by Django 5.2.7 on 2026-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='completed_by_blogger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='completed_by_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принята'), ('declined', 'Отклонена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('disputed', 'Спор')], default='pending', max_length=20),
        ),
    ]
