# Generated by Django 5.2.7 on 2026-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_deal_completed_by_blogger_deal_completed_by_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принята'), ('declined', 'Отклонена'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='pending', max_length=20),
        ),
    ]
